# This is a basic workflow to help you get started with Actions

name: Deploy to Github Pages

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the dev branch
on:
  push:
    branches: [ dev ]
  pull_request:
    branches: [ dev ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  deploy-blazor-to-github:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a single command using the runners shell
      # sets up .NET Core SDK 3.1
      - name: Setup .NET Core SDK
        uses: actions/setup-dotnet@v1.6.0
        with:
          dotnet-version: 5.0.100
              

      # publishes Blazor project to the release-folder
      - name: Publish .NET Core Project
        env:
          ACTIONS_ALLOW_UNSECURE_COMMANDS: 'true'
        run: dotnet publish spa/spa.csproj -c Release -o release --nologo
      
      # changes the base-tag in index.html from '/' to 'BlazorGitHubPagesDemo' to match GitHub Pages repository subdirectory
      - name: Change base-tag in index.html from / to "codwiz.net"
        env:
          ACTIONS_ALLOW_UNSECURE_COMMANDS: 'true'
        run: sed -i 's/<base href="\/" \/>/<base href="\/codwiz.net\/" \/>/g' release/wwwroot/index.html
      
      # copy index.html to 404.html to serve the same file when a file is not found
      - name: copy index.html to 404.html
        env:
          ACTIONS_ALLOW_UNSECURE_COMMANDS: 'true'
        run: cp release/wwwroot/index.html release/wwwroot/404.html
      
      # add .nojekyll file to tell GitHub pages to not treat this as a Jekyll project. (Allow files and folders starting with an underscore)
      - name: Add .nojekyll file
        env:
          ACTIONS_ALLOW_UNSECURE_COMMANDS: 'true'
        run: touch release/wwwroot/.nojekyll
      
      - name: Commit wwwroot to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@3.5.9
        env:
          ACTIONS_ALLOW_UNSECURE_COMMANDS: 'true'
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: gh-pages
          FOLDER: release/wwwroot
